name: mirror
favicon: null
layout_spectrum: 0.00108
typography_spectrum: 0.49721
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fe7041'
    - '#ffffff'
    - '#2f3435'
    - '#fea88b'
    - '#fec6b4'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.4877223127987236
purpose: []
